services:
  - type: web
    name: smart-healthcare-api
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: myverysecretkey123
